insert into trip (id, name, location, price, arrival_day, last_day, transport, url_image, description) values (nextval('trip_seq'), 'Isole Greche', 'Grecia', 500.00, '2024-06-3', '2024-06-7', 'Traghetto', 'https://domesstories.com/wp-content/uploads/2023/07/mykonos-chora-2.jpg', 'descrizione');
insert into trip (id, name, location, price, arrival_day, last_day, transport, url_image, description) values (nextval('trip_seq'), 'California', 'California, USA', 3000.00, '2024-08-6', '2024-08-30', 'Aereo', 'https://i0.wp.com/atravelingfairy.com/wp-content/uploads/2022/08/DSC07839-scaled.jpg?resize=1100%2C733&ssl=1.jpg', 'descrizione');
insert into trip (id, name, location, price, arrival_day, last_day, transport, url_image, description) values (nextval('trip_seq'), '日本', 'Giappone', 4000.00, '2025-03-1', '2025-03-11', 'Aereo', 'https://www.aretinatours.com/media/k2/items/cache/giappa_L.jpg', 'In questo viaggio di dieci giorni in Giappone, avrai l opportunità di esplorare tre delle città più affascinanti del Paese: Tokyo, Kanazawa e Kyoto. Inizierai con quattro giorni a Tokyo, immergendoti nella sua frenetica energia urbana e visitando luoghi iconici come il Santuario Meiji, la Shibuya Crossing e il mercato del pesce di Tsukiji. Successivamente, trascorrerai tre giorni a Kanazawa, una città ricca di storia e cultura, famosa per i suoi giardini tradizionali, i quartieri storici e l artigianato locale. Infine, concluderai il viaggio con tre giorni a Kyoto, esplorando i templi millenari, i giardini zen e le tradizioni secolari che caratterizzano questa città antica. Questo viaggio ti offrirà emozioni indimenticabili e un profondo assaggio della ricca cultura e bellezza del Giappone.');
insert into trip (id, name, location, price, arrival_day, last_day, transport, url_image, description) values (nextval('trip_seq'), 'الأردن‎', 'Giordania', 1800.00, '2024-10-4', '2024-10-12', 'Aereo', 'https://cdn.ideeperviaggiare.it/media/2018/09/antico-tempio-di-petra-in-giordania-1920x1280-11991.jpg', 'descrizione');
insert into trip (id, name, location, price, arrival_day, last_day, transport, url_image, description) values (nextval('trip_seq'), 'NYC', 'New York, USA', 1800.00, '2025-05-15', '2025-05-22', 'Aereo', 'https://www.civitatis.com/blog/wp-content/uploads/2023/03/miradores-nueva-york.jpg', 'descrizione');
insert into trip (id, name, location, price, arrival_day, last_day, transport, url_image, description) values (nextval('trip_seq'), 'Andalucia', 'Andalusia, Spagna', 600.00, '2024-07-30', '2024-08-5', 'Aereo', 'https://vamospanish.com/wp-content/uploads/must-visit-tourist-attractions-in-andalucia.jpg', 'descrizione');
insert into trip (id, name, location, price, arrival_day, last_day, transport, url_image, description) values (nextval('trip_seq'), 'Paris', 'Parigi, Francia', 500.00, '2024-08-17', '2024-08-21', 'Aereo', 'https://www.caldana.it/files/blog/image/curiosita_su_parigi_tour.jpg', 'descrizione');
insert into trip (id, name, location, price, arrival_day, last_day, transport, url_image, description) values (nextval('trip_seq'), 'Roma', 'Roma, Italia', 800.00, '2024-07-10', '2024-07-17', 'Treno', 'https://darkrome.com/media/20507/rome-vatican-city-tour-of-rome.jpg', 'descrizione');


insert into leader (id, name, surname, birthday, url_image) values (nextval('leader_seq'), 'Luca', 'Verdi', '2001-01-01', 'https://static.vecteezy.com/system/resources/previews/011/459/668/original/people-avatar-icon-png.png');
insert into leader (id, name, surname, birthday, url_image) values (nextval('leader_seq'), 'Ludovica', 'Rossi', '2002-02-02', 'https://static.vecteezy.com/system/resources/previews/011/459/669/original/people-avatar-icon-png.png');
insert into leader (id, name, surname, birthday, url_image) values (nextval('leader_seq'), 'Jake', 'White', '2003-03-03', 'https://static.vecteezy.com/system/resources/previews/011/459/666/original/people-avatar-icon-png.png');
insert into leader (id, name, surname, birthday, url_image) values (nextval('leader_seq'), 'Alessandra', 'Gialli', '2004-04-04', 'https://static.vecteezy.com/system/resources/previews/011/459/674/original/people-avatar-icon-png.png');